name = "angularclinic"
compatibility_date = "2024-10-27"

[env.production]
route = { pattern = "angularclinic.pages.dev", zone_name = "pages.dev" }

[[env.production.rules]]
type = "Text"
globs = ["**/*.html"]
headers = { "Cache-Control" = "public, max-age=300" }

[[env.production.rules]]
type = "Text"
globs = ["**/*.js", "**/*.css"]
headers = { "Cache-Control" = "public, max-age=31536000, immutable" }